import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Dashboard',
      items: ['Dashboard/Company-Overview', 'Dashboard/Booking', 'Dashboard/Tour', 'Dashboard/Transfer', 'Dashboard/Expense', 'Dashboard/Check-In', 'Dashboard/Vehicle', 'Dashboard/Guide', 'Dashboard/KPI'],
    },
    { // ขีดเส้นใต้
      type: 'html',
          value: '<hr style="border-color: black; margin: 8px 0;">',
    }, 
    {
      type: 'html',
      value: '<span style="opacity: 0.6; font-size: 14px; color:#FD5C04;">Management</span>'
    },
'Booking',
    {
      type: 'category',
      label: 'Tour',
      items: ['Tour/Manage-Group','Tour/Job-Order'],
    }
    ,
    {
      type: 'category',
      label: 'Transfer',
      items: ['Transfer/Manage-Transfer', 'Transfer/Transfer-Order'],
    }
    ,
    {
      type: 'category',
      label: 'Check In',
      items: ['Check In/Check-In', 'Check In/Check-In-List'],
    }
    ,
    {
      type: 'category',
      label: 'Expense',
      items: ['Expense/Advance', 'Expense/Actual', 'Expense/Accrued'],
    }
    ,
'Vehicle-Task'
    ,
'Guide-Task'
    ,
    { // ขีดเส้นใต้
      type: 'html',
          value: '<hr style="border-color: black; margin: 8px 0;">',
    }, 
    {
      type: 'html',
      value: '<span style="opacity: 0.6; font-size: 14px; color:#FD5C04;">Setting</span>'
    },
    {
      type: 'category',
      label: 'Program',
      items: ['Program/Program-list','Program/Items-Type','Program/Unit']
    },
'Agent' ,
    {
      type: 'category',
      label: 'Vehicle',
      items: ['Vehicle/Supplier','Vehicle/Own-vehicle', 'Vehicle/Group-Type'],
    }
    ,
'Guide-List' ,
'Zone-Transfer' ,
    {
      type:'category',
      label: 'User',
      items: ['User/User-List','User/Roles','User/Access-Log']
    }
  ],
   
};

export default sidebars;
