import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'Dashboard',
    {
      type: 'category',
      label: 'Booking',
      items: ['Booking/Overview', 'Booking/Booking-List'],
    },
    {
      type: 'category',
      label: 'Tour',
      items: ['Tour/Manage-Group','Tour/Job-Order', 'Tour/Report'],
    }
    ,
    {
      type: 'category',
      label: 'Transfer',
      items: ['Transfer/Manage-Transfer', 'Transfer/Transfer-Order', 'Transfer/Zone', 'Transfer/Report'],
    }
    ,
    {
      type: 'category',
      label: 'Check In',
      items: ['Check In/Check-In-List', 'Check In/Check-In', 'Check In/Report'],
    }
    ,
    {
      type: 'category',
      label: 'Payment',
      items: ['Payment/Advance', 'Payment/Expenses', 'Payment/Balance', 'Payment/Report'],
    }
    ,
    {
      type: 'category',
      label: 'Guide',
      items: ['Guide/Guide-List', 'Guide/Guide-Task', 'Guide/Report'],
    }
    ,
    {
      type: 'category',
      label: 'Vehicle',
      items: ['Vehicle/Supplier-List', 'Vehicle/Supplier-Task', 'Vehicle/Own-vehicle', 'Vehicle/Group-Type', 'Vehicle/Report'],
    }
    ,
    'Agent' ,
    {
      type: 'category',
      label: 'Program',
      items: ['Program/Program','Program/Items-Type','Program/Unit']
    },
    {
      type:'category',
      label: 'User',
      items: ['User/User-List','User/Roles','User/KPI', 'User/Access-Log']
    }
  ],
   
};

export default sidebars;
